### ISSUE TITLE
hi. i have a problem with tizen application

### ISSUE THREAD

**Issue by Francis0121** [socketio/socket.io-client-cpp#2]
Hi. I'm trying to build your source code to Tizen. But there is a problem. Tizen is c language based. I want to receive messages on the server in real time. I have a call using the pthread the socket_io_client () function. But the connection was successful, but the right end close () is called.
How can i use your source code in c language environment?

There socket_io_client () is in the link below.
https://github.com/Francis0121/nornenjs_v3/blob/master/client-tizen-socket-io/src/socket_io_client.cpp

**Comment by melode11** [comment]
Seems like your code reaches to the end too early, where triggers the destructor of the `sio::client`, which will call `sync_close` as well.
Try to block your execution some where.

**Comment by Francis0121** [comment]
So I wrote a while statement at the end of the source code.
(Line number:143 https://github.com/Francis0121/nornenjs_v3/blob/master/client-tizen-socket-io/src/socket_io_client.cpp) 
Like this, i can use socket event bind.

**But when I close my tizen application**, client does not **close**. At the same time server is dead.
How can i call `sio::client destructor` in the main loop?

**Comment by melode11** [comment]
1)  please use debug mode to start your server 
```bash
DEBUG=* node index.js
```
See what's happened when your server is dying.

Usually OS will close the physical connection for terminated applications. So your problem is `Server do not know client is closed` rather than  `client does not closed`. Client is actually closed, but server do not know that. It will also happen if your application is abnormally terminated or network is drop.

If you want server to know when client is closed,  please make sure to call `client.sync_close() ` once you detect your application is exiting.

Also, It is important to have some defensive code in the server side to deal with the case that client is drop without notification.

2) You can refer to the iOS demo 
https://github.com/socketio/socket.io-client-cpp/tree/master/examples/iOS
