### ISSUE TITLE
Memory management

### ISSUE THREAD

**Issue by mlantin** [socketio/socket.io-client-cpp#93]
I've just started using this library and I've got just a simple client in a loop emitting a message. At every turn around the loop it increases its memory footprint.

	sio::message::ptr msg = sio::array_message::create();
	while(true) {
			ws.socket()->emit("obj", msg);	
	}

Is there something I'm not doing to make sure memory is freed or not allocated unnecessarily?

**Comment by melode11** [comment]
The client uses a background worker thread to do the message send, so the 'emit' is a non-blocking operation, if you put in a loop, it will overwhelm the worker thread, all the messages will pending in the task queue, that's why memory footprint is high.
To resolve it , please control the emit frequency by only trigger the emitting by UI events ,timer etc.
